core_response: new jResponseStreamed
jelix/jelix pull request #379
Opened 2022-07-21 07:10 UTC by rldhont

This new response jResponseStreamed is inspired by Symphony `StreamedResponse` https://symfony.com/doc/current/components/http_foundation.html#streaming-a-response

This new response has been created to streamed content without to build a file before sending the content. For exemple to send a CSV content build from an SQL request, if the number of
lines is too heavy, it is necessary to write a file before sending the content and then dropping file.

This new response has been imagined to send a part of a file based on HTTPRange header or to send a file by chunk.

To use this new response.

* You can set the callback

```php
$rep = $this->getResponse('streamed');
$rep->mimeType = 'text/plain';
$rep->setCallback(function () {
    $iterator = range(0, 12);
    foreach ($iterator as $line) {
        sleep(1);
        echo $line;
    }
 });
return $rep;
```

* You can set the callback with use external object

```php
$rep = $this->getResponse('streamed');
$rep->mimeType = 'text/plain';
$iterator = range(0, 12);
$rep->setCallback(function () use ($iterator) {
    foreach ($iterator as $line) {
        sleep(1);
        echo $line;
    }
 });
return $rep;
```

* You can use an iterable

```php
$rep = $this->getResponse('streamed');
$rep->mimeType = 'text/plain';
$iterator = range(0, 12);
$rep->setGenerator($iterator);
return $rep;
```

* You can use a generator to get an iterable

```php
function gen($iterator) {
    foreach ($iterator as $line) {
        sleep(1);
        yield $line;
    }
}
$rep = $this->getResponse('streamed');
$rep->mimeType = 'text/plain';
$rep->setGenerator(gen($iterator));
return $rep;
```

* You can use an anonymous generator

```php
$rep = $this->getResponse('streamed');
$rep->mimeType = 'text/plain';
$rep->setGenerator((function () use ($iterator){
    foreach ($iterator as $line) {
        sleep(1);
        yield $line;
    }
})());
return $rep;
```

* You can use a class generator method

```php
protected function xrange($start, $limit, $step = 1) {
    if ($start <= $limit) {
        if ($step <= 0) {
            throw new LogicException('Step must be positive');
        }

        for ($i = $start; $i <= $limit; $i += $step) {
            yield $i;
        }
    } else {
        if ($step >= 0) {
            throw new LogicException('Step must be negative');
        }

        for ($i = $start; $i >= $limit; $i += $step) {
            yield $i;
        }
    }
}

public function getrange()
{
    $rep = $this->getResponse('streamed');
    $rep->mimeType = 'text/plain';

    $start = $this->param('start');
    $end = $this->param('end');
    $step = $this->param('step', 1);

    $rep->setGenerator($this->xrange($start, $end, $step));
    return $rep;
}
```

2022-07-21 07:54 UTC, laurentj requested changes

2022-07-21 07:54 UTC, laurentj commented on lib/jelix/core/response/jResponseStreamed.class.php
> +    protected $streamed;
it seems it is useless?

2022-07-21 07:54 UTC, laurentj commented on lib/jelix/core/response/jResponseStreamed.class.php
> +    private $headersSent;
There is already a `_httpHeadersSent` property that exists on the jResponse class, and modified by the `sendHttpHeaders()` method.  You should remove it.

2022-07-21 07:54 UTC, laurentj commented on lib/jelix/core/response/jResponseStreamed.class.php
> +        if (null === $this->callback) {
this test should be done before calling `$this->sendHttpHeaders();`, so headers for the error can be set correctly by the core of Jelix.

2022-07-21 07:54 UTC, laurentj commented on lib/jelix/core/response/jResponseStreamed.class.php
> +    public function setCallback($callback)
force the parameter type, or check the type yourself into the method: `public function setCallback(callable $callback)`

2022-07-21 07:54 UTC, laurentj commented on lib/jelix/core/response/jResponseStreamed.class.php
> +    public function setGenerator($iterator)
force the type of the parameter : `public function setGenerator(iterable $iterator)`

2022-07-21 08:05 UTC, rldhont commented
@laurentj thanks for the review. I have updated the class.

2022-09-04 06:36 UTC, laurentj approved these changes
thank you

2022-09-04 06:36 UTC, merged

2022-09-05 07:18 UTC, rldhont commented
Thanks @laurentj